intentando resolver issue #28
jokoframework/Mboehao pull request #29
Opened 2021-05-29 06:22 UTC by GonzaloGaleano

en el ejemplo se mantiene el último host configurado: 192.168.0.33
además recomiendo utilizar values/strings separados según entorno

2021-06-01 14:17 UTC, alefq requested changes
Gracias por el aporte @GonzaloGaleano , te dejé algunos comentarios para ciertos cambios necesarios por si esté dentro de tus posibilidades hacerlos.

2021-06-01 14:17 UTC, alefq commented on app/src/debug/res/values/strings.xml
> +<?xml version="1.0" encoding="utf-8"?>
Interesante recurso @GonzaloGaleano , es una buena opción para cierto tipo de constantes. 
Solemos usar el `build.gradle` para definir variables dependientes del `buildType`.

2021-06-01 14:17 UTC, alefq commented on app/src/main/res/xml/network_security_config.xml
> +    <base-config cleartextTrafficPermitted="false" />
Asegurarse de que una vez resuelto el input text para el hostname, al ingresar un nuevo hostname en runtime; se pueda conectar a un puerto plain text.

2021-06-01 14:17 UTC, alefq commented on app/src/main/java/io/github/jokoframework/activity/LoginActivity.java
> +        String url = host_name + end_point;
Sobre variable `host_name` :

1. El proyecto tiene su larga data, no obstante nuevas contribuciones tratamos de que mantengan el Coding Style de Android, como  se menciona en el README
2. Su valor debería venir de un input text en la pantalla del login. Esta funcionalidad es la más buscada del ejercicio. El objetivo es que un tester o developer,  pueda ingresar un nuevo server en runtime

2021-06-02 12:33 UTC, GonzaloGaleano commented on app/src/debug/res/values/strings.xml
> +<?xml version="1.0" encoding="utf-8"?>
si, utilizo mucho este recurso también para tener distintos iconos para la versión dev + agregando sufix a appname en build.gradle entonces poder tener debug y release instalados en el mismo teléfono y diferenciados

2021-06-02 12:35 UTC, GonzaloGaleano commented on app/src/main/java/io/github/jokoframework/activity/LoginActivity.java
> +        String url = host_name + end_point;
Si, suelo utilizar camelCase donde se puede, aquí se me pasó. Voy a estar repasando más Android Coding Style.

2021-06-02 12:38 UTC, GonzaloGaleano commented on app/src/main/res/xml/network_security_config.xml
> +    <base-config cleartextTrafficPermitted="false" />
En este caso lo resolví con un archivo solo para la versión DEBUG con base-config cleartextTrafficPermitted=true y false para la versión release. Ahí fue el siguiente pull request.

2021-06-02 12:44 UTC, GonzaloGaleano commented
Quizás hayan cosas que ajustar, pero en línea general está el prompt que solo se activa en DEBUG y setea una variable en el Singleton que se utilizará en los siguiente lugares que se requieran.
La función que levanta el prompt la hice reutilizable y la dejé en el singleton aunque podría definirse en una ClaseUtil para el mismo.

2021-08-25 15:58 UTC, alefq requested changes
Gonzalo, está resuelto en general el issue; no obstante dejo algunos comentarios para depurar un poco el código y el flujo en general; en caso de que te interese seguir con la contribución.

2021-08-25 15:58 UTC, alefq commented on app/src/debug/res/xml/network_security_config.xml
> +    <base-config cleartextTrafficPermitted="true" />
Preferimos que la opción default sea siempre segura. O utilizar un whitelist de host/domains; o que la opción sea forzar al uso de https.

2021-08-25 15:58 UTC, alefq commented on app/src/main/java/io/github/jokoframework/singleton/MboehaoApp.java
> +                            if ( inputHostName.getText().toString().equals("") ) {
Por lo general usamos `StringUtils` o algo que aplique defensive programming para prevenir valores nulos. Por ej. [string no nulo](https://github.com/jokoframework/Mboehao/blob/5d799a65c8f49dce1fa9f8ef444579e8073c6ff4/app/src/main/java/io/github/jokoframework/activity/ChangePasswordActivity.java#L59)

2021-08-25 15:58 UTC, alefq commented on app/src/main/java/io/github/jokoframework/singleton/MboehaoApp.java
> +            GoogleAnalytics.getInstance(this).setLocalDispatchPeriod(1);
¿a qué se debe este cambio? En la línea anterior se está asigando ya a un campo de la clase.

2021-08-25 15:58 UTC, alefq commented on app/src/main/java/io/github/jokoframework/otp/edit/SaveActivity.java
> +        MboehaoApp.prompDevHostName(this);
No es necesario preguntar en varias partes; el `LoginActivity` es el punto de entrada donde se requiere el valor del hostname. En los callbacks del dialog sí está bien como pusiste, aquí ya es redundante.

2021-08-25 15:58 UTC, alefq commented on app/src/main/java/io/github/jokoframework/activity/SecondAuthenticationActivity.java
> +        MboehaoApp.prompDevHostName(this);
No es necesario preguntar en varias partes; el `LoginActivity` es el punto de entrada donde se requiere el valor del hostname. En los callbacks del dialog sí está bien como pusiste, aquí ya es redundante.

2022-08-09 14:50 UTC, closed without merging