Se agrega un nuevo activity para persistir datos personales
jokoframework/Mboehao pull request #36
Opened 2022-09-16 15:20 UTC by griceldavaldez

-Se crea un nuevo activity para persistir datos personales (1)
-Se agrega (1) como un ítem más del menú

2022-09-20 11:26 UTC, alefq requested changes
Buen trabajo Grice, quedó linda la pantalla y está bueno cómo usaste los recursos de externalización para las dimensiones, textos y estilos. 💪🏽 
Te dejo una pequeña revisión antes de aceptar.

2022-09-20 11:26 UTC, alefq commented on app/src/main/res/navigation/nav_graph.xml
> +<?xml version="1.0" encoding="utf-8"?>
¿Podrías confirmar por favor si se usa para algo este archivo? 
Es probable que haya quedado desde el wizzard (asistente) para creación de nuevo activity.
Revisá por favor  y si no se usa; eliminalo por favor y actualizá el branch.

2022-09-20 20:05 UTC, griceldavaldez commented on app/src/main/res/navigation/nav_graph.xml
> +<?xml version="1.0" encoding="utf-8"?>
@alefq ya eliminé el archivo, efectivamente no se usa. Gracias profe!

2022-09-23 13:42 UTC, alefq approved these changes

2022-09-23 13:42 UTC, merged